### ISSUE TITLE
redux 版本的报错

### ISSUE THREAD

**Issue by janjon** [ant-design/antd-init#104]
```
utils.js:188uncaught at root 
 at _callee 
 at watchTodosGet 
 at watchTodosGet 
 at getTodos 
 Invariant Violation: Objects are not valid as a React child (found: SyntaxError: Unexpected token < in JSON at position 0). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
    at invariant (http://localhost:9111/index.js:278:16)
    at traverseAllChildrenImpl (http://localhost:9111/index.js:9442:56)
    at traverseAllChildren (http://localhost:9111/index.js:9470:11)
    at Object.instantiateChildren (http://localhost:9111/index.js:29303:8)
    at ReactDOMComponent._reconcilerInstantiateChildren (http://localhost:9111/index.js:34006:42)
    at ReactDOMComponent.mountChildren (http://localhost:9111/index.js:34043:28)
    at ReactDOMComponent._createInitialChildren (http://localhost:9111/index.js:31260:33)
    at ReactDOMComponent.mountComponent (http://localhost:9111/index.js:31076:13)
    at Object.mountComponent (http://localhost:9111/index.js:3495:36)
    at ReactDOMComponent.mountChildren (http://localhost:9111/index.js:34054:45)
```

求解啊！正在寻找框架

**Comment by benjycui** [comment]
首先你是否修改过 init 出来的项目。

**Comment by janjon** [comment]
@benjycui 没有改过呢，谢谢你快速回答我

**Comment by benjycui** [comment]
`antd-init@1.1.2` init 出来的没问题，建议先你本地的 antd-init 再试下。

**Comment by janjon** [comment]
@benjycui 
初始化后我就在 
```
"start": "dora -p 9222 --plugins \"proxy,webpack,webpack-hmr,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/entries/index.html\"",
```
运行后的报错是在
```
webpack:///./~/redux-saga/lib/internal/utils.js
````
错误信息是。
```
uncaught at root 
 at _callee 
 at watchTodosGet 
 at watchTodosGet 
 at getTodos 
 Invariant Violation: Objects are not valid as a React child (found: SyntaxError: Unexpected token < in JSON at position 0). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
```

我的node 版本是 v5.6

**Comment by sorrycc** [comment]
项目应用的话建议尝试 dva，配套工具是 [dva-cli](https://github.com/dvajs/dva-cli) 。

**Comment by benjycui** [comment]
> 建议先升级本地的 antd-init 再试下。

**Comment by janjon** [comment]
@sorrycc 您的这个看过 就是缺少api 请求的 utils ···

**Comment by janjon** [comment]
@benjycui 升级了也报错.我创建的无论是不是 redux 版本都会报错...

**Comment by janjon** [comment]
@benjycui 原因是我没有使用 proxy: listened on 8989
我使用的是 在 package 里  -p -9999  访问的 9999 。
