### ISSUE TITLE
Module build failed about "extract-text-webpack-plugin"

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/antd-init#112]
What I do:
1. antd-init --type redux
2. npm start

```
ERROR in ./src/entries/index.less
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch ($CWD/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/entries/index.js 37:0-23

ERROR in ./src/components/NotFound.less
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (~/git/courier-web/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/components/NotFound.jsx 17:16-42

ERROR in ./src/components/Todos/Todos.less
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/cj/git/courier-web/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/components/Todos/Todos.jsx 27:13-36

ERROR in ./src/layouts/MainLayout/MainLayout.less
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/cj/git/courier-web/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/layouts/MainLayout/MainLayout.jsx 13:18-46

ERROR in ./~/.npminstall/antd/1.9.1/antd/lib/style/index.css
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/cj/git/courier-web/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./~/.npminstall/antd/1.9.1/antd/lib/button/style/css.js 3:0-32

ERROR in ./~/.npminstall/antd/1.9.1/antd/lib/button/style/index.css
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/cj/git/courier-web/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./~/.npminstall/antd/1.9.1/antd/lib/button/style/css.js 5:0-22

ERROR in ./~/.npminstall/antd/1.9.1/antd/lib/spin/style/index.css
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/cj/git/courier-web/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./~/.npminstall/antd/1.9.1/antd/lib/spin/style/css.js 5:0-22

ERROR in ./~/.npminstall/antd/1.9.1/antd/lib/message/style/index.css
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/cj/git/courier-web/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./~/.npminstall/antd/1.9.1/antd/lib/message/style/css.js 5:0-22

ERROR in ./src/components/Todos/Todo.less
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/cj/git/courier-web/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/components/Todos/Todo.jsx 19:12-34
```

**Comment by sorrycc** [comment]
Same problem as #107. Use node 5.x or ^6.2.0 .
