### ISSUE TITLE
npm start failed.

### ISSUE THREAD

**Issue by iboying** [ant-design/antd-init#145]
1、说明：npm start 失败，找不到原因

2、env: 
node: 7.4.0

3、iTerm error info:
```
ERROR in ./src/entries/index.js
Module build failed: TypeError: Plugin 3 specified in "base" was expected to return a function but returned "undefined"
    at Function.normalisePlugin (/Users/kang/develop/react/cloud_closet_work/node_modules/.6.23.1@babel-core/lib/transformation/file/options/option-manager.js:148:15)
    at /Users/kang/develop/react/cloud_closet_work/node_modules/.6.23.1@babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/kang/develop/react/cloud_closet_work/node_modules/.6.23.1@babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/kang/develop/react/cloud_closet_work/node_modules/.6.23.1@babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/kang/develop/react/cloud_closet_work/node_modules/.6.23.1@babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/kang/develop/react/cloud_closet_work/node_modules/.6.23.1@babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/kang/develop/react/cloud_closet_work/node_modules/.6.23.1@babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/kang/develop/react/cloud_closet_work/node_modules/.6.23.1@babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/kang/develop/react/cloud_closet_work/node_modules/.6.2.10@babel-loader/lib/index.js:38:20)
 @ multi index
     livereload: Hash: 0f2e2030851392bfe565
```

4、package.json
```
"entry": {},
  "dependencies": {
    "antd": "^2.0.1",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "classnames": "^2.2.3",
    "es3ify-loader": "^0.2.0",
    "history": "^2.0.1",
    "js-cookie": "^2.1.1",
    "normalize.css": "^4.2.0",
    "rc-form": "^1.0.0",
    "rc-queue-anim": "^0.12.4",
    "rc-tween-one": "^1.0.0",
    "react-mobile-picker": "^0.1.10",
    "react-router": "^2.0.1",
    "src": "^1.1.2",
    "superagent": "^2.2.0",
    "wechat-auth": "^1.1.2",
    "wechat-oauth": "^1.1.1"
  },
  "devDependencies": {
    "atool-build": "^0.8.0",
    "babel-plugin-import": "^1.0.1",
    "babel-plugin-transform-runtime": "^6.8.0",
    "babel-runtime": "^6.9.2",
    "atool-test-mocha": "^0.1.4",
    "babel-eslint": "^6.0.2",
    "dora": "0.3.x",
    "dora-plugin-browser-history": "^0.1.1",
    "dora-plugin-livereload": "0.4.0",
    "dora-plugin-hmr": "0.6.x",
    "dora-plugin-proxy": "0.6.x",
    "dora-plugin-webpack": "0.6.x",
    "expect": "^1.20.1",
    "eslint": "^2.12.0",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-plugin-import": "^1.8.1",
    "eslint-plugin-jsx-a11y": "^1.4.2",
    "eslint-plugin-react": "^5.1.1",
    "glob": "^7.0.3",
    "pre-commit": "1.x"
  },
```

找不到原因：git reset 到之前可以的版本，依然启动不了，求助[抱拳]

**Comment by iboying** [comment]
已解决：
原来的`webpack.config.js`有如下部分：
```
  webpackConfig.babel.plugins.push(['antd', {
    style: true,  // use less if true
  }]);
```

改为：
```
webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd',
    style: true
  }]);
```

注：很早使用`ant-init`开发的一个小项目，算是遗留问题吧，应该是 `babel-plugin-import`的问题，建议大家还是用 `dva` 吧。
