### ISSUE TITLE
antd 1.0Beta版，样式覆盖报错

### ISSUE THREAD

**Issue by ottomao** [ant-design/antd-init#38]
https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme

antd 版本1.0.0-beta.9，按上述文档最后一条“样式覆盖”来操作，会有报错。v0.12没问题。

ERROR in ./src/component/AntdPatch.less
Module build failed: ModuleBuildError: Module build failed: Cannot resolve module 'antd/style/core/index.less' in /Users/Stella/workspace/simple-process/src/component
 @ /Users/Stella/workspace/simple-process/src/component/AntdPatch.less (line 16, column 0)
 near lines:
   
   @import "~antd/style/core/index.less";
   
    at DependenciesBlock.onModuleBuildFailed (/Users/Stella/workspace/simple-process/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/Stella/workspace/simple-process/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/Stella/workspace/simple-process/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/Stella/workspace/simple-process/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /Users/Stella/workspace/simple-process/node_modules/less-loader/index.js:68:16
    at /Users/Stella/workspace/simple-process/node_modules/less/lib/less/render.js:26:35
    at /Users/Stella/workspace/simple-process/node_modules/less/lib/less/parse.js:62:33
    at Object.finish [as _finish] (/Users/Stella/workspace/simple-process/node_modules/less/lib/less/parser/parser.js:180:28)
    at Object.ImportVisitor._onSequencerEmpty (/Users/Stella/workspace/simple-process/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
    at ImportSequencer.tryRun (/Users/Stella/workspace/simple-process/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
 @ ./src/component/SignStep0.jsx 19:0-27

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1558

https://github.com/ant-design/antd-init/pull/36/files
