### ISSUE TITLE
按照教程生成项目，运行时报错

### ISSUE THREAD

**Issue by hahawyman** [ant-design/antd-init#51]
win10 x64，nodejs 4.4.4，使用cnpm，antd-init 1.1.1

生成时选择 plain react - for simple project

运行时出现下面的异常
C:\MY_TEMP\antd\node_modules\.npminstall\dora\0.3.2\dora\lib\plugin.js:83
        throw new Error('[Error] ' + pluginName + ' not found in ' + resolveDir);
        ^

Error: [Error] 'webpack not found in C:\MY_TEMP\antd
    at resolvePlugin (C:\MY_TEMP\antd\node_modules\.npminstall\dora\0.3.2\dora\lib\plugin.js:83:15)
    at C:\MY_TEMP\antd\node_modules\.npminstall\dora\0.3.2\dora\lib\plugin.js:102:12
    at Array.map (native)
    at resolvePlugins (C:\MY_TEMP\antd\node_modules\.npminstall\dora\0.3.2\dora\lib\plugin.js:101:22)
    at createServer (C:\MY_TEMP\antd\node_modules\.npminstall\dora\0.3.2\dora\lib\index.js:61:44)
    at Object.<anonymous> (C:\MY_TEMP\antd\node_modules\.npminstall\dora\0.3.2\dora\bin\dora:32:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by benjycui** [comment]
Try cnpm@3

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/1790

1.1.2
