### ISSUE TITLE
antd-int指令出错

### ISSUE THREAD

**Issue by anlia260** [ant-design/antd-init#58]
/usr/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js:17
const debug = require('debug')('npminstall:bin:install');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by sorrycc** [comment]
需要升级 node 版本。
