### ISSUE TITLE
这周项目重新下载以后，install后运行报这个错，上周的时候是正常的啊

### ISSUE THREAD

**Issue by yuweilan** [ant-design/antd-init#62]
E:\react\20160527\node_modules\dora-plugin-hmr\lib\index.js:72
        loader.query.presets.push('react-hmre');
                    ^

TypeError: Cannot read property 'presets' of undefined
    at E:\react\20160527\node_modules\dora-plugin-hmr\lib\index.js:72:21
    at Array.forEach (native)
    at Object.webpackUpdateConfigFinally (E:\react\20160527\node_modules\dora-plugin-hmr\lib\index.js:70:34)
    at ret (E:\react\20160527\node_modules\dora\lib\plugin.js:140:29)
    at run (E:\react\20160527\node_modules\dora\lib\reduceAsync.js:21:5)
    at next (E:\react\20160527\node_modules\dora\lib\reduceAsync.js:14:14)
    at iteratorCallback (E:\react\20160527\node_modules\dora\lib\reduceAsync.js:23:7)
    at ret (E:\react\20160527\node_modules\dora\lib\plugin.js:113:23)
    at run (E:\react\20160527\node_modules\dora\lib\reduceAsync.js:21:5)
    at reduceAsync (E:\react\20160527\node_modules\dora\lib\reduceAsync.js:27:10)

**Comment by pigcan** [comment]
升级到 0.6.1

**Comment by yuweilan** [comment]
dora-plugin-hmr 把这个升级到0.6.1么？

**Comment by pigcan** [comment]
是的
