### ISSUE TITLE
Error w/ index.js file upon npm start 

### ISSUE THREAD

**Issue by erinjerri** [ant-design/antd-init#71]
## What you did

I typed in npm start for installing antd : https://www.npmjs.com/package/antd-init

## What you would like to happen

I would like to know if I need to update something and how to fix this problem, it is hanging on `@multi index`

## What actually happened

This is the error I received
```bash
 @ start /Users/erinpangilinan/Desktop/ant-design-master/foo
> dora -p 8001 --plugins "webpack,hmr,proxy,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/entries/index.html"

          proxy: load rule from proxy.config.js
(node:9459) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
     livereload: listening on 35729
temp certs cleared
📦  1/3 build modulesGenerating RSA private key, 2048 bit long modulus
.......+++
..............................+++
e is 65537 (0x10001)
=============
rootCA generated at :
/Users/erinpangilinan/.anyproxy_certs
=============
rootCA generated
please trust the rootCA.crt in /Users/erinpangilinan/.anyproxy_certs/
or you may get it via anyproxy webinterface
📦  15/16 build modules
webpack: bundle build is now finished.
Hash: 6b55309a6d794ead80bd
Version: webpack 1.12.15
Time: 38298ms
        Asset     Size  Chunks             Chunk Names
    common.js  24.3 kB       0  [emitted]  common
     index.js  80.1 kB    1, 0  [emitted]  index
common.js.map  25.7 kB       0  [emitted]  common
 index.js.map  87.8 kB    1, 0  [emitted]  index
chunk    {0} common.js, common.js.map (common) 0 bytes [rendered]
chunk    {1} index.js, index.js.map (index) 77.8 kB {0} [rendered]
    [0] multi index 40 bytes {1} [built] [1 error]
    [1] ./~/html-entities/lib/html5-entities.js 49 kB {1} [built]
    [2] ./~/ansi-html/index.js 4.02 kB {1} [built]
    [3] ./~/ansi-regex/index.js 135 bytes {1} [built]
    [4] ./~/html-entities/index.js 231 bytes {1} [built]
    [5] ./~/html-entities/lib/html4-entities.js 6.57 kB {1} [built]
    [6] ./~/html-entities/lib/xml-entities.js 2.98 kB {1} [built]
    [7] ./~/querystring/decode.js 2.4 kB {1} [built]
    [8] ./~/querystring/encode.js 2.09 kB {1} [built]
    [9] ./~/querystring/index.js 127 bytes {1} [built]
   [10] ./~/strip-ansi/index.js 161 bytes {1} [built]
   [11] (webpack)-hot-middleware/client-overlay.js 1.73 kB {1} [built]
   [12] (webpack)-hot-middleware/client.js?path=http://127.0.0.1:8001/__webpack_hmr 4.18 kB {1} [built]
   [13] (webpack)-hot-middleware/process-update.js 3.88 kB {1} [built]
   [14] (webpack)/buildin/module.js 251 bytes {1} [built]

ERROR in ./src/entries/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/erinpangilinan/Desktop/ant-design-master"
    at /Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
    at OptionManager.mergeOptions (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at OptionManager.addConfig (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/index.js:140:24)
 @ multi index
     livereload: Hash: 6b55309a6d794ead80bd
Version: webpack 1.12.15
Time: 38298ms
        Asset     Size  Chunks             Chunk Names
    common.js  24.3 kB       0  [emitted]  common
     index.js  80.1 kB    1, 0  [emitted]  index
common.js.map  25.7 kB       0  [emitted]  common
 index.js.map  87.8 kB    1, 0  [emitted]  index
chunk    {0} common.js, common.js.map (common) 0 bytes [rendered]
chunk    {1} index.js, index.js.map (index) 77.8 kB {0} [rendered]
    [0] multi index 40 bytes {1} [built] [1 error]
    [1] ./~/html-entities/lib/html5-entities.js 49 kB {1} [built]
    [2] ./~/ansi-html/index.js 4.02 kB {1} [built]
    [3] ./~/ansi-regex/index.js 135 bytes {1} [built]
    [4] ./~/html-entities/index.js 231 bytes {1} [built]
    [5] ./~/html-entities/lib/html4-entities.js 6.57 kB {1} [built]
    [6] ./~/html-entities/lib/xml-entities.js 2.98 kB {1} [built]
    [7] ./~/querystring/decode.js 2.4 kB {1} [built]
    [8] ./~/querystring/encode.js 2.09 kB {1} [built]
    [9] ./~/querystring/index.js 127 bytes {1} [built]
   [10] ./~/strip-ansi/index.js 161 bytes {1} [built]
   [11] (webpack)-hot-middleware/client-overlay.js 1.73 kB {1} [built]
   [12] (webpack)-hot-middleware/client.js?path=http://127.0.0.1:8001/__webpack_hmr 4.18 kB {1} [built]
   [13] (webpack)-hot-middleware/process-update.js 3.88 kB {1} [built]
   [14] (webpack)/buildin/module.js 251 bytes {1} [built]

ERROR in ./src/entries/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "~/Desktop/ant-design-master"
    at $CWD/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
    at OptionManager.mergeOptions (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at OptionManager.addConfig (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/erinpangilinan/Desktop/ant-design-master/foo/node_modules/babel-core/lib/transformation/file/index.js:140:24)
 @ multi index
```

## Environment Information

- antd v 1.1.2 https://www.npmjs.com/package/antd-init
- OSX 10.11.0 Beta El Capitan
- Chrome Version 51.0.2704.84 (64-bit)

**Comment by sorrycc** [comment]
Is there a `babelrc` file in your project directory or user directory? The build tool we supplied does not require the `es2015` presets.
